- name: Commit & Push
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add epg.xml.gz
          git commit -m "Auto-update EPG" || exit 0
          git pull --rebase origin main
          git push
